updating favicon and resizing navbar logo
dexidp/website pull request #24
Opened 2020-10-09 23:01 UTC by nate-double-u

- Updating favicon as per issue https://github.com/dexidp/website/issues/15
- Resizing logo as per issue https://github.com/dexidp/website/issues/12

2020-10-09 23:02 UTC, nate-double-u commented
Preview URL: https://deploy-preview-24--dexidp.netlify.app/

2020-10-14 00:15 UTC, celestehorgan requested changes
:grima

2020-10-14 00:15 UTC, celestehorgan commented on layouts/partials/navbar.html
> +          <img src="{{ $url }}" width="85">
😬 

Sorry nate, this was me, moving too fast and not cleaning up after myself.

Would it be possible to add a `class="blah"` to this instead and then set the width via the `_custom.sass` file instead?

2020-10-15 19:57 UTC, celestehorgan approved these changes

2020-10-15 20:07 UTC, merged